version: '4.21.1'
services:
  app:
    build: .
    volumes:
      - .:/django_demo
    image: app:django_demo
    container_name: django_container
    # command: gunicorn -c gunicorn.py hello.wsgi:application

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    depends_on:
      - app
