version: '3'
services:
  djangoapp:
    image: demofordjango.azurecr.io/django_demo:1.0
    container_name: django_container
    expose:
      - 8000  
    environment:
      - DEBUG=True
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "4", "hello.wsgi:application"]
    networks:
      - my_network

  nginx:
    image: demofordjango.azurecr.io/nginx
    container_name: nginx_container
    ports:
      - "80:80"  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  
    depends_on:
      - djangoapp
    networks:
      - my_network

networks:
  my_network:
    external: true  
