version: '4.21.1'
services:
  app:
    depends_on:
      - db
    build: .
    volumes:
      - .:/django_demo
    ports:
      - 8000:8000
    image: app:django_demo
    container_name: django_container
    environment:
      MYSQL_DATABASE: django_demo
      MYSQL_USER: root
      MYSQL_PASSWORD: acer
      MYSQL_HOST: db
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: acer
      MYSQL_DATABASE: django_demo

    volumes:
      - ./data/mysql:/var/lib/mysql
