version: '4.21.1'
services:
  app:
    build: .
    volumes:
      - .:/django_demo
    ports:
      - 8000:8000
    image: app:django_demo
    container_name: django_container
    command: gunicorn -c gunicorn.py hello.wsgi:application
    